feat(HMS-3587): Add blueprint_version field to /composes
osbuild/image-builder pull request #1046
Opened 2024-02-21 09:57 UTC by amirfefer

Image builder UI fetches `/composes` and render its data in "All Images" Table.
Following the new blueprint layout, the table has a new column for the corresponding blueprint's version, but the `blueprint_version` field exists only in the specific blueprints/{id}/composes endpoint.

2024-02-21 12:46 UTC, lzap requested changes
Also needs a rebase.

2024-02-27 09:58 UTC, lzap submitted a review, later dismissed

2024-04-02 08:45 UTC, lzap commented
Somehow missed this one sorry, can you rebase?

2024-04-02 09:13 UTC, ezr-ondrej requested changes
We're missing the openapi spec change, should we have that? or is it in the spec already?

2024-04-02 09:15 UTC, ezr-ondrej approved these changes
Sorry, it's there! Just rebase pls :pray:

2024-04-02 09:15 UTC, lzap commented
From our scrum: we were putting this one on hold since this is a stable API change, but we have realized the API change was already done. Let’s rebase and get it in.

2024-04-11 12:15 UTC, amirfefer commented
@lzap . @ezr-ondrej  - rebased

2024-04-11 13:56 UTC, ezr-ondrej commented
/retest

2024-04-12 06:54 UTC, ezr-ondrej commented
/retest

2024-04-12 07:46 UTC, merged