server: Allow filtering on org_id from the identity header
osbuild/image-builder pull request #107
Opened 2021-01-19 15:50 UTC by Gundersanne

For now when the environment is empty the filter won't apply.

2021-01-24 11:17 UTC, teg requested changes
Love it! This is exactly what we need :) One nitpick, and there were a couple of warnings about missing tests. Could you either add the tests, or add a comment to the commit message to say why not?

2021-01-24 11:17 UTC, teg commented on internal/server/server.go
>  		// decode the b64 string and check a specific entitlement
We decode it now, so drop the comment?

2021-01-25 12:40 UTC, Gundersanne commented
@teg I added a bunch of unit tests. The integration tests only test the expect path. Do you want me to replicate the unit tests in the integration tests?

2021-01-25 15:05 UTC, teg commented
Nah, no need to replicate the tests. I'm totally fine with saying "the warnings are moot because of reasons". Just thought I'd ask since we have them enabled ;)

2021-01-25 15:08 UTC, Gundersanne commented
Oh, i tuned those out automatically, probably a bad reflix! Hm I could easily add a test for one of those. I'll do that and then ask for a rereview :)

2021-01-25 15:18 UTC, teg commented
> Oh, i tuned those out automatically, probably a bad reflix! Hm I could easily add a test for one of those. I'll do that and then ask for a rereview :)

Hehe, I know the reflex. Reviewers are here to tune them back in :P

2021-01-25 16:01 UTC, teg approved these changes
Great! Thanks for this!

2021-01-25 16:01 UTC, merged