Add test steps into README
osbuild/image-builder pull request #111
Opened 2021-01-26 15:35 UTC by yuxisun1217

Signed-off-by: Yuxin Sun <yuxisun@redhat.com>

2021-01-27 11:40 UTC, teg reviewed
Thanks for this @yuxisun1217! This looks great! I'll let @Gundersanne have a look before merging, but looks good to me!

2021-01-27 12:09 UTC, Gundersanne requested changes
Thanks! Looks good, some minor change requests.

2021-01-27 12:09 UTC, Gundersanne commented on README.md
> +    * https://github.com/osbuild/image-builder-frontend
I think we can leave the image-builder-frontend and insights-proxy setup out of the image-builder readme.

2021-01-27 12:09 UTC, Gundersanne commented on README.md
> +2. Setting up the proxy
See above, the proxy is not required to run the integration tests.

2021-01-27 12:09 UTC, Gundersanne commented on README.md
> +* https://osbuildci.cloud.paas.psi.redhat.com/me/my-views/view/all/job/osbuild/job/image-builder/job/main/
This is an internal url, personally don't think it should be in the public readme.

2021-01-28 15:37 UTC, yuxisun1217 commented
Thank @Gundersanne ! I removed the image-builder-frontend and insights-proxy repos, removed CI section, and cut some redundant words. Please help to review again.

2021-01-28 15:41 UTC, yuxisun1217 commented
BTW, what's our custom here if I want to change code in a PR? Force push to the same commit or create a new commit into the same branch? I used to force push before. Thanks!

2021-01-28 17:35 UTC, Gundersanne approved these changes
Nice, thank you

Force pushing is best, alternatively adding commits on top and then using github to squash is also fine (though that only works when there needs to be only 1 commit merged in the end).

2021-01-28 17:35 UTC, merged