v1: add /experimental/blueprints/{id}/imageTypes endpoint to image builder (HMS-4066)
osbuild/image-builder pull request #1180
Opened 2024-05-09 12:49 UTC by mgold1234

This commit introduces a new endpoint that retrieves a list of image types for a specific blueprint image. It also adds a handler function to implement this endpoint. Additionally, unit tests are included to verify the functionality of this new endpoint.

2024-05-09 13:17 UTC, ezr-ondrej reviewed
I thought we'll use the `/blueprints/{uuid}` endpoint and extract it on the frontend, but if we think we need this, this looks correct :)

2024-05-09 13:17 UTC, ezr-ondrej commented on internal/v1/api.yaml
> +  /experimental/blueprints/{id}/imageTypes:
I belive we should use lowercase in API `image_types`

2024-05-09 13:59 UTC, lzap submitted a review, later dismissed
I am fine, what @ezr-ondrej said.

2024-05-09 13:59 UTC, lzap commented on internal/v1/handler_blueprints.go
> +	return ctx.JSON(http.StatusOK, imageTypes)
Why do you create new `BlueprintResponse` only to use `blueprintResponse.ImageRequests`? This can be simplified.

2024-05-09 13:59 UTC, lzap commented on internal/v1/api.yaml
> +                  $ref: '#/components/schemas/ImageTypes'
It is not a good practice to return anything else than a dictionary. Probably okay for this endpoint, it is experimental after all. I am good.

2024-05-12 20:09 UTC, mgold1234 commented
/retest

2024-05-13 07:46 UTC, lzap approved these changes
Great work.

2024-05-13 07:46 UTC, lzap commented on internal/v1/handler_blueprints.go
> +	var imageTypes []ImageTypes
Just a nitpick, you do not have to rebase this here we only have 3 elements but it is good to do this if you know the length in advance:

```suggestion
	imageTypes := make([]ImageTypes, 0, len(blueprint))
```

2024-05-13 07:46 UTC, lzap commented on internal/v1/handler_blueprints_test.go
> +	}
You could use [ElementsMatch](https://pkg.go.dev/github.com/stretchr/testify/require#ElementsMatch), there are many useful functions in that package. But this is okay.

2024-05-13 07:48 UTC, ezr-ondrej approved these changes
Thanks! :+1:

2024-05-13 07:49 UTC, ezr-ondrej commented
/retest

2024-05-13 08:51 UTC, lzap requested changes
As we just found out, the data is already exposed through `GetBlueprint` so there is no need for this. Sorry for not catching it up earlier.

2024-05-13 12:26 UTC, closed without merging