ci(HMS-3962): Update Integration test image for IQE
osbuild/image-builder pull request #1217
Opened 2024-06-03 10:14 UTC by akhil-jha

Name update from hms-integration to insights-experiences.

2024-06-03 10:17 UTC, akhil-jha commented
@jrusz

2024-06-03 13:21 UTC, ezr-ondrej commented
@akhil-jha the kube-linter is unhappy. Do you think we can fix that, or shall we adjust the linter?

```
The container "image-builder-iqe--tests-image_tag-v0hqck" is using an invalid container image, "quay.io/cloudservices/iqe-tests". Please use images that are not blocked by the `BlockList` criteria : [".*:(latest)$" "^[^:]*$" "(.*/[^:]+)$"] (check: latest-tag, remediation: Use a container image with a specific tag other than latest.)
```

2024-06-04 07:32 UTC, jrusz requested changes

2024-06-04 07:32 UTC, jrusz commented on templates/iqe-trigger-integration.yml
> +  value: quay.io/cloudservices/iqe-tests
```suggestion
  value: quay.io/cloudservices/iqe-tests:insights-experiences
```
I guess let's add this here, that should make the linter happy and it makes sense to me to have a tag there.

2024-06-13 11:13 UTC, jrusz commented
/retest

2024-06-13 11:14 UTC, jrusz commented
/retest

2024-06-13 11:17 UTC, jrusz approved these changes

2024-06-13 13:52 UTC, jrusz commented
/retest

2024-06-14 06:42 UTC, jrusz commented
/retest

2024-06-14 07:16 UTC, merged