Makefile: Add coverage-report target
osbuild/image-builder pull request #1322
Opened 2024-08-29 08:13 UTC by mgold1234

This commit introduces a new 'coverage-report' target to the Makefile, enhancing the developer's ability to analyze code coverage directly from the terminal.

The new target allows developers to:
- Generate a comprehensive coverage report for the entire project

This addition streamlines the code coverage review process, enabling developers to quickly focus on particular areas of interest within the codebase.

2024-08-29 08:59 UTC, schuellerf approved these changes
nice, thanks

2024-08-30 10:38 UTC, schuellerf requested changes
Oh - overlooked this, please add `coverage.html` to `.gitignore`

2024-09-02 08:47 UTC, schuellerf submitted a review, later dismissed

2024-09-02 08:47 UTC, schuellerf commented on Makefile
> +	@echo "    coverage-dump:     Run unit tests and display function-level coverage information."
tiny nit-pick? but I'll approve anyway
```suggestion
	@echo "    coverage-dump:      Run unit tests and display function-level coverage information."
```

2024-09-04 17:02 UTC, schuellerf requested changes
`coverage.out` should not be part of the git commit, I guess
although this is not mentioned in the `Makefile` maybe also add it to `.gitignore` (after removing from git)

2024-10-01 09:00 UTC, schuellerf requested changes

2024-10-01 09:00 UTC, schuellerf commented on Makefile
> +coverage-dump: unit-tests
This target seems to be duplicated?

2024-10-01 09:20 UTC, mvo5 reviewed
Thank you for this PR. I added a small comment/question inline, once the double "coverage-dump" is clarified/fixed this is good to go from my PoV

2024-10-01 09:20 UTC, mvo5 commented on Makefile
> +coverage-dump: unit-tests
It looks like this stanza is a duplicate of the one in line 65. We probably only need one "coverage-dump" target or am I missing something? (copy/paste issue maybe?)

2024-10-01 09:20 UTC, mvo5 commented on .gitignore
> +
(super nitick) extra newlines here that we probably don't need (but they also don't hurt so fine to ignore)

2024-10-01 10:16 UTC, mgold1234 commented on Makefile
> +coverage-dump: unit-tests
thanks

2024-10-01 10:25 UTC, mvo5 approved these changes
Thank you!

2024-10-01 11:20 UTC, schuellerf approved these changes
Thank you!

2024-10-01 11:55 UTC, merged