handlers: extract `makeTestServer()` test helper
osbuild/image-builder pull request #1354
Opened 2024-09-25 08:15 UTC by mvo5

While reviewing PR#1350 I noticed that there is some repetition that could be extracted into a common helper. This commit does this and adds a new `makeTestServer()` that creates the DB, starts the db and token servers and passes a cleanup/shutdown helper back.

2024-09-25 08:34 UTC, lzap submitted a review, later dismissed

2024-10-23 12:57 UTC, mvo5 commented
@croissanne added you mostly for awareness - I think this is okay (and the PR got a +1 already) but I I really like you being in the loop :)

2024-10-25 13:25 UTC, croissanne requested changes
LGTM but seems like the linter found a tiny thing?

2024-10-28 08:26 UTC, mvo5 commented
> LGTM but seems like the linter found a tiny thing?

Indeed, there was drift because the PR was old and new code with db_srv got added nice, should be fixed now :)

2024-10-29 11:31 UTC, merged