server: expand openapi spec
osbuild/image-builder pull request #174
Opened 2021-04-23 13:09 UTC by chloenayon

Expand the openapi to describe content and parameters more specifically,
also edit some of the tests to reflect changes from the addition of the input 
validation logic.

2021-04-23 14:16 UTC, Gundersanne requested changes
I like the spec changes! Have some comments on the added tests. 

And maybe we could add a unit test for the `uniqueItems` constraint as well? So for those we could add a test with multiple items, and a test with multiple items with a duplicate item.

2021-04-23 14:16 UTC, Gundersanne commented on internal/server/server_test.go
> +		response, body = tutils.GetResponseBody(t, "http://localhost:8086/api/image-builder/v1/packages?distribution=rhel-8&architecture=x86_64&search=ssh&limit=10", &tutils.AuthString0)
Why up the limit to 10 here? I think testing the edges and just over the edges (so limit=1 and limit=0) is a good idea.

2021-04-23 14:16 UTC, Gundersanne commented on internal/server/server_test.go
> +		response, _ = tutils.GetResponseBody(t, "http://localhost:8086/api/image-builder/v1/packages?distribution=rhel-8&architecture=x86_64&search=ssh&limit=13", &tutils.AuthString0)
I'd rather keep the negative values here and check it returns 400, the good cases are already tested above

2021-04-23 14:16 UTC, Gundersanne commented on internal/server/server_test.go
> -		response, _ = tutils.GetResponseBody(t, "http://localhost:8086/api/image-builder/v1/packages?distribution=rhel-8&architecture=x86_64&search=ssh&limit=-13&offset=-2193", &tutils.AuthString0)
How about we change this into a positive limit and a negative offset (and then check it returns 400?)

2021-04-23 14:16 UTC, Gundersanne commented on internal/server/server_test.go
> +		response, body = tutils.GetResponseBody(t, "http://localhost:8086/api/image-builder/v1/packages?distribution=rhel-8&architecture=x86_64&search=ssh&limit=-10", &tutils.AuthString0)
We should test this inded, but how about we just convert the last coupel of cases in this test to test invalid values?

2021-04-27 10:16 UTC, chloenayon commented on internal/server/server_test.go
> +		require.Regexp(t, "image_requests/0/upload_request/options|image_requests/0/upload_request/type", body)
It seems that the order in which openapi3filter checks for invalid input is not strict - I've seen both of these errors regularly and both are equally technically correct, hence this change from require.Contains to require.Regexp in order to catch both.

2021-04-29 11:03 UTC, Gundersanne approved these changes
Thank youuuuuuuuuu

2021-04-29 11:03 UTC, merged