dnf-json: Fetch from osbuild-composer when needed
osbuild/image-builder pull request #223
Opened 2021-07-20 15:06 UTC by lavocatt

dnf-json is fetched from
https://raw.githubusercontent.com/osbuild/osbuild-composer/main/dnf-json
and is no more versioned in this repo.

2021-07-20 16:10 UTC, Gundersanne requested changes
Thanks!

`dnf-json` needs to be marked as executable as well. After writing the file add `os.chmod(DNF_JSON, 0o744)`.  You can test quite easily using `tools/generate-package-lists --distro ./distributions/centos-8.json` or another distro.

2021-07-20 16:10 UTC, Gundersanne commented on tools/generate-package-lists
> +r = requests.get("https://raw.githubusercontent.com/osbuild/osbuild-composer/main/dnf-json")
I'd move the actual request into the main function, under the argument parsing. On top it's just the definition of the constants.

2021-07-20 16:10 UTC, Gundersanne commented on tools/generate-package-lists
> +with open(os.path.join(PROJECT_ROOT, "dnf-json"), 'w') as f:
When moved below, could just use the DNF_JSON constant instead of the path.join.

2021-07-21 07:31 UTC, lavocatt commented
> Thanks!
> 
> `dnf-json` needs to be marked as executable as well. After writing the file add `os.chmod(DNF_JSON, 0o744)`. You can test quite easily using `tools/generate-package-lists --distro ./distributions/centos-8.json` or another distro.

Indeed ! I was testing it with `./tools/generate-package-lists` only which obviously didn't thrown any bad exception.

2021-07-21 08:23 UTC, Gundersanne approved these changes
Thanks!

2021-07-26 12:14 UTC, merged