CI: Update test runners to 8.4 GA
osbuild/image-builder pull request #252
Opened 2021-09-10 10:15 UTC by atodorov

Depends on https://github.com/osbuild/gitlab-ci-terraform/pull/21

2021-09-10 10:36 UTC, Gundersanne approved these changes
lgtm, adding blocked until that PR is merged.

2021-09-10 11:26 UTC, ondrejbudai commented
Note that the new rhel-8.4-ga images are all pre-subscribed by the gitlab executor. Therefore https://github.com/osbuild/image-builder/blob/b8039afe8483f1f6986b3001b09aca56bc8ed125/schutzbot/deploy.sh#L15 can/should be removed.

2021-09-15 11:07 UTC, Gundersanne requested changes
Thanks, just one issue.

2021-09-15 11:07 UTC, Gundersanne commented on schutzbot/deploy.sh
> +    #!/bin/bash
Needs a whitespace fix.

2021-09-15 11:17 UTC, Gundersanne approved these changes

2021-09-15 12:04 UTC, Gundersanne commented
Adding blocked for https://github.com/osbuild/gitlab-ci-terraform/pull/22

2021-09-15 12:23 UTC, Gundersanne approved these changes

2021-09-16 14:32 UTC, merged