Add constraints that account_number can't be an empty string
osbuild/image-builder pull request #253
Opened 2021-09-10 10:51 UTC by lavocatt

See #240

2021-09-10 15:10 UTC, Gundersanne requested changes
Thanks! Some thoughts

2021-09-10 15:44 UTC, lavocatt commented on internal/db/migrations/3_add_alter_table_composes.up.sql
> +ALTER TABLE IF EXISTS composes ADD  CONSTRAINT PK_org_id CHECK ((account_number<>N''));
Oh yeah this, I really stack overflowed this one at it seemed to work so... gonna change the stuff you required.
I don't really know this much in sql btw

2021-09-10 15:46 UTC, lavocatt commented on cmd/image-builder-db-test/main_test.go
> +	"testing"
You can thank my vim plugin ^^ it does it automatically when I save a file :smile:

2021-09-10 15:51 UTC, Gundersanne commented on cmd/image-builder-db-test/main_test.go
> +	"testing"
that is a good idea, I'll do that too :>

2021-09-10 16:09 UTC, lavocatt commented on internal/tutils/idheader_utils.go
> +var noOrgIdIdHeader string = "{" +
Good idea!

2021-09-13 11:01 UTC, Gundersanne approved these changes
LGTM, thank you!

For future reference, `UnitTests:` in the commit topic can point to the name of the module, so in this case `v1`, or `server`.

2021-09-13 11:31 UTC, merged