add rhel-85 to package endpoint
osbuild/image-builder pull request #293
Opened 2021-11-13 01:25 UTC by matoval

Add rhel-85 to /package endpoint

2021-11-15 11:33 UTC, Gundersanne approved these changes

2021-11-15 11:34 UTC, Gundersanne requested changes
Thank you, missed that. 

Can you run `/tools/prepare-source.sh` and push again? It should generate the api, which is why the checks are complaining.

2021-11-15 11:37 UTC, teg commented
Would be good to have some tests for this, I think.

2021-11-15 11:38 UTC, Gundersanne commented
> Would be good to have some tests for this, I think.

agreed, I can do that in a followup

2021-11-15 17:37 UTC, Gundersanne approved these changes
lgtm, thanks!

2021-11-16 08:57 UTC, ondrejbudai approved these changes

2021-11-16 11:12 UTC, Gundersanne commented
The gcp failure is unrelated, I'll merge this since it's relatively high priority.

2021-11-16 11:13 UTC, merged