image-builder: log a warning msg when glitchtip not initialized
osbuild/image-builder pull request #977
Opened 2024-01-05 16:04 UTC by diaasami

2024-01-08 11:46 UTC, ochosi reviewed
The PR description is empty, but the change makes sense to me. Wondering if it would make sense to not only refer to Sentry but also GlitchTip, because someone less familiar with the subject may be looking for that in the logs.

2024-01-08 11:46 UTC, ochosi commented on cmd/image-builder/main.go
> +		log.Warn("Sentry was not initialized")
How about adding a reference to the GlitchTip name as well?

2024-01-08 12:26 UTC, croissanne requested changes

2024-01-08 14:45 UTC, croissanne commented on cmd/image-builder/main.go
> +
Empty newline

2024-01-08 14:45 UTC, croissanne commented on cmd/image-builder/main.go
> -	"github.com/labstack/gommon/log"
We still need log to set the level.

2024-01-10 16:42 UTC, croissanne approved these changes

2024-01-10 16:42 UTC, merged